language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - 'pip install pipenv'
  - 'pipenv install'
script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'